# -*- coding: utf-8 -*-
"""task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBcDBNLpR9mpQ2Tk7NyyGyhsUzDSHha_

Imports
"""

import os
import cv2
import random
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from tqdm import tqdm
import pickle
from multiprocessing import Pool
import shutil
from sklearn.model_selection import train_test_split
import torchvision.transforms as T
import matplotlib.pyplot as plt

# Define directory paths
video_dir = "videos/"
train_dir = "train_videos/"
eval_dir = "eval_videos/"
test_dir = "test_videos/"
model_dir = "model/"
augmented_dir = "augmented_videos/"

# Create directories if they don’t exist
for folder in [video_dir, train_dir, eval_dir, test_dir,augmented_dir, model_dir]:
    os.makedirs(folder, exist_ok=True)

print("Directories successfully created")

# Check if CUDA is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\nUsing device: {device}")

#FUNCTION: Check if video is valid
def is_video_valid(video_path):
    """Checks if a video file is valid and not empty."""
    cap = cv2.VideoCapture(video_path)
    valid = cap.isOpened() and int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) > 0
    cap.release()
    return valid

#FUNCTION: Flip video (horizontal or vertical)
def flip_video(video_path, output_path, mode):
    """Flips a video (horizontal or vertical) and saves it."""
    cap = cv2.VideoCapture(video_path)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    frame_width, frame_height = int(cap.get(3)), int(cap.get(4))
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    if frame_width == 0 or frame_height == 0 or fps == 0:
        return False  # Skip invalid video

    out = cv2.VideoWriter(output_path, fourcc, fps, (frame_width, frame_height))

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        frame = cv2.flip(frame, mode)  # Flip mode: 1 (Horizontal), 0 (Vertical)
        out.write(frame)

    cap.release()
    out.release()

    return is_video_valid(output_path)


#GET ORIGINAL VIDEOS
original_videos = [os.path.join(video_dir, f) for f in os.listdir(video_dir) if f.endswith('.mp4')]

if not original_videos:
    print("No videos found in the source directory.")
else:
    print("\nAugmenting Videos\n")

    for idx, video_path in enumerate(original_videos, start=1):
        video_name = os.path.splitext(os.path.basename(video_path))[0]
        print(f"Processing: {video_name} ({idx}/{len(original_videos)})")

        # Clone videos
        cloned_videos = []
        clone_count = 6  # Number of clones per video

        with tqdm(total=clone_count, desc=f"Cloning {video_name}", unit="file") as pbar:
            for i in range(1, clone_count + 1):
                cloned_path = os.path.join(augmented_dir, f"{video_name}_clone_{i}.mp4")
                shutil.copy(video_path, cloned_path)
                cloned_videos.append(cloned_path)
                pbar.update(1)  # Update progress bar

        # Shuffle clones and split into categories
        random.shuffle(cloned_videos)
        mirror_count = int(0.45 * clone_count)  # 30% for mirroring
        flip_count = int(0.45 * clone_count)    # 30% for flipping
        mirror_set = cloned_videos[:mirror_count]
        flip_set = cloned_videos[mirror_count:mirror_count + flip_count]
        original_set = cloned_videos[mirror_count + flip_count:]  # Remaining 40%

        # Apply Mirroring (Horizontal Flip)
        with tqdm(total=len(mirror_set), desc=f"Mirroring {video_name}", unit="file") as pbar:
            for clone_path in mirror_set:
                mirrored_path = clone_path.replace(".mp4", "_mirrored.mp4")
                if flip_video(clone_path, mirrored_path, mode=1):  # mode=1 for horizontal flip
                    os.remove(clone_path)
                pbar.update(1)  # Update progress bar

        # Apply Flipping (Vertical Flip)
        with tqdm(total=len(flip_set), desc=f"↕Flipping {video_name}", unit="file") as pbar:
            for clone_path in flip_set:
                flipped_path = clone_path.replace(".mp4", "_flipped.mp4")
                if flip_video(clone_path, flipped_path, mode=0):  # mode=0 for vertical flip
                    os.remove(clone_path)
                pbar.update(1)  # Update progress bar

    #COUNT TOTAL AUGMENTED VIDEOS
    total_augmented_videos = len([f for f in os.listdir(augmented_dir) if f.endswith('.mp4')])
    print(f"\nTotal videos in '{augmented_dir}': {total_augmented_videos}\n")

# Split Augmented Videos into Train (70%) & Eval (30%)

all_augmented_videos = [os.path.join(augmented_dir, f) for f in os.listdir(augmented_dir) if f.endswith('.mp4')]
train_videos, eval_videos = train_test_split(all_augmented_videos, test_size=0.3, random_state=42)

for v in train_videos:
    shutil.move(v, os.path.join(train_dir, os.path.basename(v)))

for v in eval_videos:
    shutil.move(v, os.path.join(eval_dir, os.path.basename(v)))


for v in original_videos:
    shutil.copy(v, os.path.join(test_dir, os.path.basename(v)))

print(f"Train videos: {len(os.listdir(train_dir))}")
print(f"\nEvaluation videos: {len(os.listdir(eval_dir))}")
print(f"\nTest video: {len(os.listdir(test_dir))}")

def compute_optical_flow(video_path):
    """Computes optical flow to estimate movement (x, y) for each frame."""
    cap = cv2.VideoCapture(video_path)
    ret, prev_frame = cap.read()

    if not ret:
        raise ValueError(f"Could not read video: {video_path}")

    prev_gray = cv2.cvtColor(prev_frame, cv2.COLOR_BGR2GRAY)
    path = []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        flow = cv2.calcOpticalFlowFarneback(prev_gray, gray, None, 0.5, 3, 15, 3, 5, 1.2, 0)
        dx, dy = np.mean(flow[..., 0]), np.mean(flow[..., 1])
        path.append([dx, dy])
        prev_gray = gray

    cap.release()
    return np.array(path) if path else np.zeros((1, 2))

def save_optical_flow(video_folder, save_path):
    """Computes and saves optical flow for all videos in a given folder."""
    video_files = sorted([os.path.join(video_folder, f) for f in os.listdir(video_folder) if f.endswith(".mp4")])
    flow_data = {}

    print(f"\nProcessing videos in '{video_folder}' ({len(video_files)} found)...")

    for video_path in tqdm(video_files, desc=f"Processing {video_folder}", unit="video"):
        path = compute_optical_flow(video_path)
        flow_data[video_path] = path
        tqdm.write(f"✔ Processed {os.path.basename(video_path)} | Optical Flow Shape: {path.shape}")

    with open(save_path, "wb") as f:
        pickle.dump(flow_data, f)

    print(f"Optical flow saved to {save_path}")

# Precompute and Save Optical Flow
if not os.path.exists("train_flow.pkl"):
    save_optical_flow("train_videos", "train_flow.pkl")
    save_optical_flow("eval_videos", "eval_flow.pkl")
    save_optical_flow("test_videos", "test_flow.pkl")

def count_videos(directory):
    return len([f for f in os.listdir(directory) if f.endswith(".mp4")])

train_count = count_videos("train_videos")
eval_count = count_videos("eval_videos")
test_count = count_videos("test_videos")
videos_count = count_videos("videos")
print(f"Videos: {videos_count}")
print(f"Train Videos: {train_count}")
print(f"Eval Videos: {eval_count}")
print(f"Test Videos: {test_count}")

class VideoDataset(Dataset):
    def __init__(self, video_folder, flow_file, max_seq_len=742, apply_augmentations=True):
        self.video_files = sorted([
            os.path.join(video_folder, f) for f in os.listdir(video_folder) if f.endswith(".mp4")
        ])
        self.max_seq_len = max_seq_len
        self.apply_augmentations = apply_augmentations

        # Load optical flow data
        with open(flow_file, "rb") as f:
            self.flow_data = pickle.load(f)

        # Define Augmentations
        self.augment = T.Compose([
            T.RandomHorizontalFlip(p=0.5),
            T.RandomRotation(degrees=15),
            T.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.3, hue=0.1),
            T.GaussianBlur(kernel_size=(3, 3), sigma=(0.1, 2.0)),
            T.RandomResizedCrop(size=(64, 64), scale=(0.8, 1.0))
        ])

    def __len__(self):
        return len(self.video_files)

    def __getitem__(self, idx):
        video_path = self.video_files[idx]
        frames = self.load_video_frames(video_path)
        path = self.flow_data.get(video_path, np.zeros((self.max_seq_len, 2)))

        frames = self.pad_or_truncate(frames)
        path = self.pad_or_truncate_path(path)

        return frames, torch.tensor(path, dtype=torch.float32), video_path

    def load_video_frames(self, video_path):
        cap = cv2.VideoCapture(video_path)
        frames = []

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (64, 64))

            # Convert to PyTorch Tensor
            frame = torch.tensor(frame, dtype=torch.float32) / 255.0  # Normalize to [0,1]
            frame = frame.permute(2, 0, 1)  # Convert to (C, H, W)

            # 🔹 Apply Augmentations (only during training)
            if self.apply_augmentations and torch.rand(1).item() < 0.8:
                frame = self.augment(frame)

            frames.append(frame)

        cap.release()

        if len(frames) == 0:
            return torch.zeros((1, 3, 64, 64))  # Return empty tensor if no frames

        return torch.stack(frames)

    def pad_or_truncate(self, frames):
        num_frames = frames.shape[0]
        if num_frames > self.max_seq_len:
            return frames[:self.max_seq_len]  # Truncate
        else:
            pad_size = self.max_seq_len - num_frames
            return torch.cat((frames, torch.zeros((pad_size, 3, 64, 64))), dim=0)  # Pad

    def pad_or_truncate_path(self, path):
        num_frames = path.shape[0]
        if num_frames > self.max_seq_len:
            return path[:self.max_seq_len]  # Truncate
        else:
            pad_size = self.max_seq_len - num_frames
            return np.vstack((path, np.zeros((pad_size, 2))))

class CNNLSTM(nn.Module):
    def __init__(self, hidden_dim=512, num_layers=2, dropout=0.3):
        super(CNNLSTM, self).__init__()

        # CNN Feature Extractor
        self.cnn = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )

        # Fully Connected Layer
        self.fc = nn.Linear(256 * 8 * 8, 512)  # Adjusted to avoid overfitting
        self.dropout = nn.Dropout(dropout)

        # LSTM for Temporal Features
        self.lstm = nn.LSTM(
            input_size=512, hidden_size=hidden_dim, num_layers=num_layers,
            batch_first=True, dropout=dropout, bidirectional=False
        )

        # Output Layer
        self.layer_norm = nn.LayerNorm(hidden_dim)  # Helps stabilize training
        self.classifier = nn.Linear(hidden_dim, 2)  # No activation here

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.shape

        # Merge batch & sequence dimension
        x = x.view(batch_size * seq_len, c, h, w)

        # CNN Feature Extraction
        x = self.cnn(x)
        x = torch.flatten(x, start_dim=1)
        x = self.fc(x)
        x = self.dropout(x)

        # Reshape for LSTM
        x = x.view(batch_size, seq_len, -1)

        # LSTM for sequence modeling
        x, _ = self.lstm(x)
        x = self.layer_norm(x)  # Normalize LSTM output

        # Output layer
        return self.classifier(x)  # No tanh (allows more flexible outputs)

# Datasets
train_dataset = VideoDataset("train_videos", "train_flow.pkl", apply_augmentations=True)
eval_dataset = VideoDataset("eval_videos", "eval_flow.pkl", apply_augmentations=False)
test_dataset = VideoDataset("test_videos", "test_flow.pkl", apply_augmentations=False)

# Loaders
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)  # Increased batch size
eval_loader = DataLoader(eval_dataset, batch_size=4, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

# Model
model = CNNLSTM().to(device)

#  Xavier Weight Initialization
def init_weights(m):
    if isinstance(m, nn.Linear) or isinstance(m, nn.Conv2d):
        nn.init.xavier_uniform_(m.weight)
        if m.bias is not None:
            nn.init.zeros_(m.bias)

model.apply(init_weights)  # Apply weights before training


def train(model, train_loader, eval_loader, epochs=300, model_dir="model/"):
    os.makedirs(model_dir, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    criterion = nn.MSELoss()  # Change loss function if needed
    optimizer = optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-4)  # AdamW for better stability
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)


    best_val_loss = float("inf")
    patience = 15
    patience_counter = 0
    accumulation_steps = 2

    train_losses = []
    val_losses = []

    for epoch in range(epochs):
        model.train()
        total_train_loss = 0
        optimizer.zero_grad()

        print(f"\nEpoch {epoch+1}/{epochs}")

        # Single Training Progress Bar
        with tqdm(total=len(train_loader), desc="Training", unit="batch", leave=True, dynamic_ncols=True) as train_progress:
            for i, (batch, targets, _) in enumerate(train_loader):
                batch, targets = batch.to(device), targets.to(device)
                output = model(batch)
                #loss = criterion(output, targets) / accumulation_steps
                loss = criterion(output, targets)  # Compute loss first
                loss = loss / accumulation_steps  # Normalize loss before accumulating gradients
                loss.backward()

                if (i + 1) % accumulation_steps == 0:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                    optimizer.step()
                    optimizer.zero_grad()

                total_train_loss += loss.item() * accumulation_steps
                avg_train_loss = total_train_loss / (i + 1)

                # Update Progress Bar
                train_progress.set_postfix(train_loss=f"{avg_train_loss:.4f}")
                train_progress.update(1)

        avg_train_loss = total_train_loss / len(train_loader)
        train_losses.append(avg_train_loss)

        # Validation Loop
        model.eval()
        total_val_loss = 0

        with tqdm(total=len(eval_loader), desc="Validating", unit="batch", leave=True, dynamic_ncols=True) as val_progress:
            with torch.no_grad():
                for i, (batch, targets, _) in enumerate(eval_loader):
                    batch, targets = batch.to(device), targets.to(device)
                    output = model(batch)
                    loss = criterion(output, targets).item()
                    total_val_loss += loss

                    avg_val_loss = total_val_loss / (i + 1)

                    # Update Progress Bar
                    val_progress.set_postfix(val_loss=f"{avg_val_loss:.4f}")
                    val_progress.update(1)

        avg_val_loss = total_val_loss / len(eval_loader)
        val_losses.append(avg_val_loss)

        print(f"Epoch {epoch+1} | Train Loss: {avg_train_loss:.6f} | Validation Loss: {avg_val_loss:.6f}")

        # Learning rate adjustment
        scheduler.step(avg_val_loss)
        print(f"Current Learning Rate: {optimizer.param_groups[0]['lr']}")

        # Save best model
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            patience_counter = 0
            model_path = os.path.join(model_dir, "best_model.pth")
            torch.save(model.state_dict(), model_path)
            print(f"Model improved! Saved to {model_path}")
        else:
            patience_counter += 1

        # Early stopping
        if patience_counter >= patience:
            print(f"Early Stopping at Epoch {epoch+1}")
            break

    # Plot Loss Curves
    plot_loss_curves(train_losses, val_losses)


# Function to Plot Training & Validation Loss
def plot_loss_curves(train_losses, val_losses):
    plt.figure(figsize=(10, 5))
    plt.plot(train_losses, label="Train Loss", marker='o')
    plt.plot(val_losses, label="Validation Loss", marker='o')
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.title("Training & Validation Loss Curve")
    plt.legend()
    plt.grid(True)
    plt.show()

# Start Training
print("\nInitiating Training:")
train(model, train_loader, eval_loader, epochs=300)

def test(model, test_loader):
    model.eval()
    best_video = None
    best_score = float("inf")

    with torch.no_grad():
        for frames, _, video_paths in test_loader:
            frames = frames.to(device)
            output = model(frames).cpu().numpy()

            for i, video_name in enumerate(video_paths):
                frame_outputs = output[i]  # Model predictions per frame

                # Penalize SHARP turns (sudden direction changes)
                sharp_turn_penalty = np.sum(np.abs(np.diff(frame_outputs, n=2)))

                # Allow smooth diagonal motion (by using first-order differences)
                smooth_motion_score = np.sum(np.abs(np.diff(frame_outputs)))

                # Slight penalty for longer videos
                time_penalty = len(frame_outputs) * 0.05

                # Final Score: Balance between straight and smooth diagonal motion
                score = sharp_turn_penalty * 1.5 + smooth_motion_score * 0.5 + time_penalty

                if score < best_score:
                    best_score = score
                    best_video = video_name

    print("\nBest Path Video:", best_video)
test(model, test_loader)